# Generated by Django 4.1.1 on 2022-09-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTable',
            fields=[
                ('train_seq', models.AutoField(primary_key=True, serialize=False, verbose_name='운동정보 순번')),
                ('train_info', models.TextField(verbose_name='운동 정보')),
                ('train_img', models.ImageField(upload_to='', verbose_name='운동 이미지')),
            ],
            options={
                'verbose_name': '운동정보 테이블',
                'db_table': 't_train2',
            },
        ),
    ]
