# Generated by Django 4.1.1 on 2022-09-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_trainingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTable',
            fields=[
                ('column_seq', models.AutoField(primary_key=True, serialize=False, verbose_name='컬럼 순번')),
                ('column_title', models.CharField(max_length=400, verbose_name='컬럼 제목')),
                ('column_content', models.TextField(verbose_name='컬럼 내용')),
                ('column_img', models.ImageField(upload_to='', verbose_name='컬럼 이미지')),
                ('column_link', models.CharField(max_length=400, verbose_name='컬럼 출처')),
                ('column_date', models.DateField(auto_now_add=True, verbose_name='컬럼 날짜')),
            ],
            options={
                'verbose_name': '컬럼정보 테이블',
                'db_table': 't_column2',
            },
        ),
    ]
