# Generated by Django 4.1.1 on 2022-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='구분')),
                ('name', models.CharField(max_length=50, verbose_name='시설명')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('tel', models.CharField(max_length=50, verbose_name='전화번호')),
            ],
        ),
    ]
