# Generated by Django 4.1.1 on 2022-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
            ],
            options={
                'verbose_name': '이미지테스트1',
                'db_table': 'imagetest1',
            },
        ),
    ]
