# Generated by Django 4.1.1 on 2022-09-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('upload_file', models.ImageField(blank=True, null=True, upload_to='image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.members')),
            ],
            options={
                'verbose_name': '이미지테스트2',
                'db_table': 'imgtest2',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('mem_seq', models.AutoField(primary_key=True, serialize=False)),
                ('exam_img', models.ImageField(upload_to='', verbose_name='검사 이미지')),
                ('exam_date', models.DateTimeField(auto_now_add=True, verbose_name='검사 날짜')),
                ('exam_result', models.TextField(verbose_name='검사 결과')),
                ('mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.members', verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': '검사 테이블2',
                'db_table': 't_exam2',
            },
        ),
    ]
