# Generated by Django 4.1.1 on 2022-09-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_test1_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('mem_seq', models.AutoField(primary_key=True, serialize=False)),
                ('exam_img', models.ImageField(upload_to='', verbose_name='검사 이미지')),
                ('exam_date', models.DateTimeField(auto_now_add=True, verbose_name='검사 날짜')),
                ('exam_result', models.TextField(verbose_name='검사 결과')),
                ('mem_id', models.CharField(max_length=200, verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': 'test2',
                'db_table': 'test2',
            },
        ),
    ]
