# Generated by Django 4.1.1 on 2022-09-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('predict', '0004_person_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test3',
            fields=[
                ('mem_seq', models.AutoField(primary_key=True, serialize=False)),
                ('exam_img', models.ImageField(upload_to='', verbose_name='검사 이미지')),
                ('exam_date', models.DateTimeField(auto_now_add=True, verbose_name='검사 날짜')),
                ('exam_result', models.TextField(verbose_name='검사 결과')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.members', verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': '검사 테이블3',
                'db_table': 't_exam3',
            },
        ),
    ]
