# Generated by Django 4.1.1 on 2022-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_column='member_id', max_length=50)),
                ('passwd', models.CharField(db_column='passwd', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='y', max_length=10)),
                ('reg_date', models.DateTimeField(auto_now_add=True, db_column='reg_date')),
                ('update_date', models.DateTimeField(auto_now_add=True, db_column='update_date')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('mem_id', models.CharField(default=False, max_length=20, primary_key=True, serialize=False, verbose_name='회원 아이디')),
                ('mem_pw', models.TextField(verbose_name='회원 비밀번호')),
                ('mem_name', models.CharField(default=False, max_length=30, verbose_name='회원 이름')),
                ('mem_birth', models.DateField(verbose_name='회원 생년월일')),
                ('mem_gender', models.CharField(max_length=1, verbose_name='회원 성별')),
                ('mem_joindate', models.DateField(auto_now_add=True, verbose_name='회원 가입일자')),
                ('mem_type', models.CharField(max_length=1, verbose_name='회원 유형')),
            ],
            options={
                'verbose_name': '회원 테이블',
                'db_table': 't_member',
            },
        ),
    ]
