# Generated by Django 4.1.1 on 2022-09-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTable',
            fields=[
                ('mem_id', models.CharField(default=False, max_length=20, primary_key=True, serialize=False, verbose_name='회원 아이디')),
                ('mem_pw', models.TextField(verbose_name='회원 비밀번호')),
                ('mem_name', models.CharField(default=False, max_length=30, verbose_name='회원 이름')),
                ('mem_birth', models.DateField(verbose_name='회원 생년월일')),
                ('mem_gender', models.CharField(max_length=1, verbose_name='회원 성별')),
                ('mem_joindate', models.DateField(verbose_name='회원 가입일자')),
                ('mem_type', models.CharField(max_length=1, verbose_name='회원 유형')),
            ],
            options={
                'verbose_name': '회원 테이블',
                'db_table': 't_member2',
            },
        ),
    ]
