# Generated by Django 4.1.1 on 2022-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointable',
            name='mem_joindate',
            field=models.DateField(auto_now_add=True, verbose_name='회원 가입일자'),
        ),
    ]
