# Generated by Django 4.1.1 on 2022-10-04 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('game_seq', models.AutoField(primary_key=True, serialize=False, verbose_name='게임 순번')),
                ('game_score1', models.IntegerField(verbose_name='최고 점수1')),
                ('game_score2', models.IntegerField(verbose_name='최고 점수2')),
                ('game_score3', models.IntegerField(verbose_name='최고 점수3')),
                ('game_score4', models.IntegerField(verbose_name='최고 점수4')),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.members', verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': '게임 테이블',
                'db_table': 't_game2',
            },
        ),
    ]
